/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CharactersImport } from './routes/characters'
import { Route as IndexImport } from './routes/index'
import { Route as EncountersIndexImport } from './routes/encounters/index'
import { Route as EncountersEncounterIdImport } from './routes/encounters/$encounterId'

// Create/Update Routes

const CharactersRoute = CharactersImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const EncountersIndexRoute = EncountersIndexImport.update({
  id: '/encounters/',
  path: '/encounters/',
  getParentRoute: () => rootRoute,
} as any)

const EncountersEncounterIdRoute = EncountersEncounterIdImport.update({
  id: '/encounters/$encounterId',
  path: '/encounters/$encounterId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/characters': {
      id: '/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersImport
      parentRoute: typeof rootRoute
    }
    '/encounters/$encounterId': {
      id: '/encounters/$encounterId'
      path: '/encounters/$encounterId'
      fullPath: '/encounters/$encounterId'
      preLoaderRoute: typeof EncountersEncounterIdImport
      parentRoute: typeof rootRoute
    }
    '/encounters/': {
      id: '/encounters/'
      path: '/encounters'
      fullPath: '/encounters'
      preLoaderRoute: typeof EncountersIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/characters': typeof CharactersRoute
  '/encounters/$encounterId': typeof EncountersEncounterIdRoute
  '/encounters': typeof EncountersIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/characters': typeof CharactersRoute
  '/encounters/$encounterId': typeof EncountersEncounterIdRoute
  '/encounters': typeof EncountersIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/characters': typeof CharactersRoute
  '/encounters/$encounterId': typeof EncountersEncounterIdRoute
  '/encounters/': typeof EncountersIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/characters' | '/encounters/$encounterId' | '/encounters'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/characters' | '/encounters/$encounterId' | '/encounters'
  id:
    | '__root__'
    | '/'
    | '/characters'
    | '/encounters/$encounterId'
    | '/encounters/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CharactersRoute: typeof CharactersRoute
  EncountersEncounterIdRoute: typeof EncountersEncounterIdRoute
  EncountersIndexRoute: typeof EncountersIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CharactersRoute: CharactersRoute,
  EncountersEncounterIdRoute: EncountersEncounterIdRoute,
  EncountersIndexRoute: EncountersIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/characters",
        "/encounters/$encounterId",
        "/encounters/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/characters": {
      "filePath": "characters.tsx"
    },
    "/encounters/$encounterId": {
      "filePath": "encounters/$encounterId.tsx"
    },
    "/encounters/": {
      "filePath": "encounters/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
